name: decimals
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2 # Use the latest version
  audioplayers: ^6.1.1
  http:  ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/decimal1.png
    - assets/kids.jpeg
    - assets/decimal2.png
    - assets/bird.jpg
    - assets/background.jpeg
    - assets/fish.png
    - assets/bird.jpg
    - assets/bird.png
    - assets/orangefish.png
    - assets/backgroundlake.jpg
    - assets/sounds/error.mp3
    - assets/sounds/success.mp3
    - assets/demo1.jpg
    - assets/finalbackground.jpg
    - assets/play.jpg
    - assets/matchitbackground.png
    - assets/b2.png
    - assets/l2.png
    - assets/top2.png
    
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
